package iso.tool;
import javax.swing.*; import java.awt.*; import java.nio.file.*;
/** Unified ISO-Tool feature-button GUI. */
public final class UnifiedGui extends JFrame {
 private final JTextField source=new JTextField("."); private final JTextArea log=new JTextArea(); private final JLabel status=new JLabel("Ready");
 private static final String[][] G={{"Source & Repository","Open GitHub","Clone Repository","Open Local Source","Open Archive","Deep Recursive Scan","Repository Tree","Dependency Analysis","Application Discovery"},{"Toolchains","Detect Windows Toolchains","Detect MSVC","Detect Clang","Detect GCC/G++","Detect NASM","Bootstrap NASM","Bootstrap GCC/G++","Built-in Spit Fire Assembler"},{"Build","Generate Build Plan","Compile","Link","Debug Build","Release Build","GNU Build","MSVC Build","Build All Projects","Run Tests","Build Journal"},{"ISO / Boot","Build Spit Fire Boot Sector","Build BIOS ISO","Build UEFI ISO","Build BIOS + UEFI ISO","Build ISO Image","Build IMG","Merge Binaries","Merge Libraries","Generate Manifest","Verify Boot Image","Verify ISO"},{"Packages / Applications","Detect Package Managers","Install Dependencies","Application Inventory","Artifact Inventory"},{"Diagnostics","Validate Configuration","Dependency Errors","Runtime Errors","Build Errors","View Logs","Export Diagnostics","Verify Output"}};
 public UnifiedGui(){super("ISO-Tool — Source → Build → Spit Fire → Bootable ISO");setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1240,820));setLayout(new BorderLayout(8,8));JPanel top=new JPanel(new BorderLayout(8,8));top.setBorder(BorderFactory.createEmptyBorder(12,12,0,12));top.add(new JLabel("Source / GitHub / local checkout:"),BorderLayout.WEST);top.add(source,BorderLayout.CENTER);JButton browse=new JButton("Browse…");browse.addActionListener(e->choose());top.add(browse,BorderLayout.EAST);add(top,BorderLayout.NORTH);JPanel rows=new JPanel();rows.setLayout(new BoxLayout(rows,BoxLayout.Y_AXIS));for(String[] g:G){JPanel row=new JPanel(new FlowLayout(FlowLayout.LEFT,5,3));JLabel l=new JLabel(g[0]+":");l.setPreferredSize(new Dimension(170,28));row.add(l);for(int i=1;i<g.length;i++){JButton b=new JButton(g[i]);b.addActionListener(e->run(((JButton)e.getSource()).getText()));row.add(b);}rows.add(row);}add(new JScrollPane(rows),BorderLayout.CENTER);log.setEditable(false);log.setFont(new Font(Font.MONOSPACED,Font.PLAIN,12));JScrollPane lp=new JScrollPane(log);lp.setPreferredSize(new Dimension(1240,220));JPanel bottom=new JPanel(new BorderLayout());bottom.add(lp,BorderLayout.CENTER);JPanel sb=new JPanel(new BorderLayout());sb.setBorder(BorderFactory.createEmptyBorder(4,12,8,12));sb.add(status,BorderLayout.WEST);bottom.add(sb,BorderLayout.SOUTH);add(bottom,BorderLayout.SOUTH);append("ISO-Tool GUI ready; unified feature contract loaded.");}
 private void choose(){JFileChooser c=new JFileChooser();c.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);if(c.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)source.setText(c.getSelectedFile().toPath().toString());}
 private void run(String f){status.setText(f+" — running");append("[feature] "+f);try{if(f.equals("Deep Recursive Scan")||f.equals("Repository Tree")){Path r=Paths.get(source.getText()).toAbsolutePath();try(var s=Files.walk(r)){append("[scan] recursive files="+s.filter(Files::isRegularFile).count());}}else append("[dispatch] "+f+" source="+source.getText());status.setText(f+" — complete");}catch(Exception ex){append("[error] "+ex);status.setText(f+" — failed");}}
 private void append(String s){log.append(s+System.lineSeparator());} public static void launch(){SwingUtilities.invokeLater(()->new UnifiedGui().setVisible(true));}
}
