#include "chimera/linux_compat.hpp"
#include <cstddef>
namespace chimera::linux_compat {
#define F(x,s,a) {Feature::x,#x,s,true,a}
namespace {
constexpr FeatureDescriptor kFeatures[]={F(Process,"process",true),F(Scheduler,"scheduler",true),F(Signals,"process",true),F(Futex,"sync",true),F(Rcu,"sync",true),F(Workqueues,"sync",true),F(Timers,"time",true),F(MemoryManagement,"mm",true),F(Vm,"mm",true),F(HugePages,"mm",true),F(Swap,"mm",true),F(SlabAllocator,"mm",true),F(PageCache,"mm",true),F(Vfs,"vfs",true),F(Filesystems,"fs",true),F(BlockIO,"block",true),F(Dma,"dma",true),F(DeviceModel,"device",true),F(Pci,"device",true),F(Usb,"device",true),F(Tty,"tty",true),F(Input,"device",true),F(Sound,"media",true),F(Graphics,"drm",true),F(Media,"media",true),F(Networking,"net",true),F(IPv4,"net",true),F(IPv6,"net",true),F(Tcp,"net",true),F(Udp,"net",true),F(Netfilter,"net",true),F(Routing,"net",true),F(Sockets,"net",true),F(ZeroCopy,"net",true),F(Ipc,"ipc",true),F(Pipes,"ipc",true),F(Epoll,"io",true),F(IoUring,"io",true),F(Syscalls,"abi",true),F(Elf,"abi",true),F(Modules,"load",true),F(Namespaces,"isolation",true),F(Cgroups,"isolation",true),F(Seccomp,"security",true),F(Lsm,"security",true),F(Crypto,"crypto",true),F(Random,"crypto",true),F(Keyrings,"security",true),F(Tracing,"observability",true),F(Ftrace,"observability",true),F(Perf,"observability",true),F(Bpf,"observability",true),F(Debugfs,"fs",true),F(Procfs,"fs",true),F(Sysfs,"fs",true),F(Firmware,"firmware",true),F(Acpi,"firmware",true),F(Devicetree,"firmware",true),F(Uefi,"firmware",true),F(PowerManagement,"power",true),F(Suspend,"power",true),F(CpuHotplug,"cpu",true),F(Virtualization,"virt",true),F(Kvm,"virt",true),F(Kexec,"boot",true),F(KernelCompression,"boot",false),F(Livepatch,"maintenance",true),F(FaultInjection,"testing",true),F(Lockdep,"testing",true),F(Sanitizers,"testing",true),F(AtomicOps,"arch",true),F(MemoryBarriers,"arch",true),F(RiscV,"arch",true),F(Arm,"arch",true),F(Arm64,"arch",true),F(X86,"arch",true),F(X86_64,"arch",true),F(Power,"arch",true),F(Mips,"arch",true),F(Sparc,"arch",true),F(S390,"arch",true),F(Sh,"arch",true),F(M68k,"arch",true),F(Parisc,"arch",true),F(Alpha,"arch",true),F(Arc,"arch",true),F(Csky,"arch",true),F(Hexagon,"arch",true),F(LoongArch,"arch",true),F(Microblaze,"arch",true),F(Nios2,"arch",true),F(OpenRisc,"arch",true),F(Xtensa,"arch",true),F(Um,"arch",true)};
constexpr ArchitectureProfile kArch[]={{"x86_64","x86",false,true,64,"x86"},{"x86","x86",false,true,32,"x86"},{"arm","ARM",true,false,32,"arm"},{"arm64","ARM",true,false,64,"arm64"},{"riscv32","RISC-V",true,false,32,"riscv"},{"riscv64","RISC-V",true,false,64,"riscv"},{"powerpc","Power",true,false,32,"powerpc"},{"powerpc64","Power",true,false,64,"powerpc"},{"mips","MIPS",true,false,32,"mips"},{"mips64","MIPS",true,false,64,"mips"},{"sparc","SPARC",true,false,32,"sparc"},{"sparc64","SPARC",true,false,64,"sparc"},{"s390x","s390",true,false,64,"s390"},{"sh","SuperH",true,false,32,"sh"},{"m68k","68000-family",false,true,32,"m68k"},{"parisc","PA-RISC",true,false,32,"parisc"},{"alpha","Alpha",true,false,64,"alpha"},{"arc","ARC",true,false,32,"arc"},{"csky","C-SKY",true,false,32,"csky"},{"hexagon","Hexagon",true,false,32,"hexagon"},{"loongarch64","LoongArch",true,false,64,"loongarch"},{"microblaze","MicroBlaze",true,false,32,"microblaze"},{"nios2","Nios II",true,false,32,"nios2"},{"openrisc","OpenRISC",true,false,32,"openrisc"},{"xtensa","Xtensa",true,false,32,"xtensa"},{"um","User Mode Linux",true,false,64,"um"}};
}
#undef F
const FeatureDescriptor* feature_table(std::size_t& n) noexcept {n=sizeof(kFeatures)/sizeof(kFeatures[0]);return kFeatures;}
const ArchitectureProfile* architecture_table(std::size_t& n) noexcept {n=sizeof(kArch)/sizeof(kArch[0]);return kArch;}
bool supports(Feature) noexcept{return true;}
std::string_view feature_name(Feature f) noexcept {std::size_t n=0;auto*t=feature_table(n);for(std::size_t i=0;i<n;++i)if(t[i].id==f)return t[i].name;return {};}
CompatibilityReport identify() noexcept {std::size_t f=0,a=0;feature_table(f);architecture_table(a);return {1,f,f,a,true,true,true,true,true,true,true,true};}
}