#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd -- "$(dirname -- "$0")/../.." && pwd)"
OUT="${ROOT}/runtime/commands/ss64"
python3 "${ROOT}/tools/ss64/chimera-ss64-arabic-aliases.py" "$@"
mkdir -p "${ROOT}/runtime/shell"
cat > "${ROOT}/runtime/shell/chimera-arabic-aliases.sh" <<'EOF'
# Generated by Chimera II OS. Source only in an interactive shell.
CHIMERA_ALIAS_DIR="${CHIMERA_ALIAS_DIR:-/usr/share/chimera/commands/ss64}"
if [ -d "$CHIMERA_ALIAS_DIR" ]; then
  for f in "$CHIMERA_ALIAS_DIR"/*.bash_aliases; do
    [ -r "$f" ] && . "$f"
  done
fi
EOF
printf '[OK] Arabic SS64 alias runtime generated under %s\n' "$OUT"
