#!/usr/bin/env bash

# --- Chimera II OS standard help ---
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  cat <<'CHIMERA_HELP'
Chimera II OS script: tools/ss64/install-ss64-arabic-aliases.sh

Usage:
  tools/ss64/install-ss64-arabic-aliases.sh [options] [arguments]

Options:
  -h, --help    Show this help and exit successfully.

Notes:
  This help entry is provided consistently across Chimera II OS shell tools.
  The script's existing command-line interface and environment variables remain unchanged.
CHIMERA_HELP
  exit 0
fi
set -euo pipefail
ROOT="$(cd -- "$(dirname -- "$0")/../.." && pwd)"
OUT="${ROOT}/runtime/commands/ss64"
python3 "${ROOT}/tools/ss64/chimera-ss64-arabic-aliases.py" "$@"
mkdir -p "${ROOT}/runtime/shell"
cat > "${ROOT}/runtime/shell/chimera-arabic-aliases.sh" <<'EOF'
# Generated by Chimera II OS. Source only in an interactive shell.
CHIMERA_ALIAS_DIR="${CHIMERA_ALIAS_DIR:-/usr/share/chimera/commands/ss64}"
if [ -d "$CHIMERA_ALIAS_DIR" ]; then
  for f in "$CHIMERA_ALIAS_DIR"/*.bash_aliases; do
    [ -r "$f" ] && . "$f"
  done
fi
EOF
printf '[OK] Arabic SS64 alias runtime generated under %s\n' "$OUT"
