services:
  chimera-build:
    build: .
    image: amerhwitat/chimeraiios:local
    container_name: chimeraiios-build
    volumes:
      - chimera-build-cache:/tmp/chimera-build
    init: true
volumes:
  chimera-build-cache:
