#include "../include/chimera/koronos_abi.h"
#include "chimera/scheduler.h"
#include "chimera/driver.h"
#include "chimera/learning.h"
#include "chimera/multiboot_modules.h"
#include "chimera/hardware.h"
#include "chimera/device.h"
#include "chimera/firmware.h"
extern "C" void koronos_outb(uint16_t port,uint8_t value);
namespace {
volatile uint32_t koronos_state=0;
static uint8_t serial_in8(uint16_t port){uint8_t v;__asm__ volatile("inb %1,%0":"=a"(v):"Nd"(port));return v;}
static void serial_init(){koronos_outb(0x3F9,0);koronos_outb(0x3FB,0x80);koronos_outb(0x3F8,3);koronos_outb(0x3F9,0);koronos_outb(0x3FB,3);koronos_outb(0x3FA,0xC7);koronos_outb(0x3FC,3);}
static void serial_write8(uint8_t v){for(uint32_t i=0;i<100000u&&!(serial_in8(0x3FD)&0x20);++i){}koronos_outb(0x3F8,v);}
static void serial_write(const char*s){if(!s)return;while(*s)serial_write8((uint8_t)*s++);serial_write8('\r');serial_write8('\n');}
static void vga_clear(){volatile uint16_t*v=(volatile uint16_t*)0xB8000;for(uint32_t i=0;i<80u*25u;i++)v[i]=0x0720;}
static void vga_write(const char*s){volatile uint16_t*v=(volatile uint16_t*)0xB8000;static uint32_t row=0,col=0;if(row==0&&col==0){vga_clear();}if(!s)return;while(*s){char c=*s++;if(c=='\r'){col=0;continue;}if(c=='\n'){col=0;if(++row>=25)row=24;continue;}if(col>=80){col=0;if(++row>=25)row=24;}v[row*80+col++]=(uint16_t)(0x0F00u|(uint8_t)c);}}
static void console_write(const char*s){serial_write(s);vga_write(s);vga_write("\r\n");}
static void console_u32(uint32_t v){char s[11];uint32_t i=10;s[i]=0;if(v==0){console_write("0");return;}while(v&&i){s[--i]=(char)('0'+v%10u);v/=10u;}console_write(&s[i]);}
static void console_hex32(uint32_t v){static const char h[]="0123456789ABCDEF";char s[9];for(int i=7;i>=0;--i){s[i]=h[v&15u];v>>=4;}s[8]=0;console_write(s);}
static const char*module_kind_name(uint32_t k){switch(k){case CHIMERA_MODULE_LIVE_INITRAMFS:return "LIVE INITRAMFS";case CHIMERA_MODULE_LIVE_MANIFEST:return "LIVE MANIFEST";case CHIMERA_MODULE_INSTALL_IMAGE:return "INSTALL IMAGE";case CHIMERA_MODULE_INSTALL_MANIFEST:return "INSTALL MANIFEST";case CHIMERA_MODULE_INSTALL_CONTRACT:return "INSTALL CONTRACT";case CHIMERA_MODULE_INSTALL_PHASES:return "INSTALL PHASES";case CHIMERA_MODULE_INSTALL_PROFILES:return "INSTALL PROFILES";default:return "OTHER";}}
static void console_modules(){uint32_t n=chimera_multiboot_module_count();console_write("[MB2 ] Module registry: ");console_u32(n);console_write(" module(s)");for(uint32_t i=0;i<n;i++){const chimera_boot_module*m=chimera_multiboot_module(i);console_write("[MB2 ] type=");console_write(module_kind_name(m->kind));console_write("[MB2 ] cmdline=");console_write(m->cmdline);console_write("[MB2 ] base=");console_hex32((uint32_t)m->base);console_write("[MB2 ] size=");console_hex32((uint32_t)m->size);}}
static volatile uint32_t console_task_runs=0,module_task_runs=0,live_task_runs=0,installer_phase=0;
static void task_console(void*){if(console_task_runs++==0)console_write("[TASK] Console service online");}
static void task_modules(void*){if(module_task_runs++==0){console_write("[TASK] Module manager online");console_modules();}}
static void task_live(void*){if(live_task_runs++==0){const chimera_boot_module*m=chimera_multiboot_find(CHIMERA_MODULE_LIVE_INITRAMFS);if(m){console_write("[LIVE] Live initramfs module accepted");console_write("[LIVE] Runtime handoff queued");chimera_sched_block();}else if(!chimera_multiboot_find(CHIMERA_MODULE_INSTALL_IMAGE)){console_write("[LIVE] No live initramfs module; live service idle");chimera_sched_block();}}}
static void task_installer(void*){const chimera_boot_module*image=chimera_multiboot_find(CHIMERA_MODULE_INSTALL_IMAGE);const chimera_boot_module*manifest=chimera_multiboot_find(CHIMERA_MODULE_INSTALL_MANIFEST);const chimera_boot_module*contract=chimera_multiboot_find(CHIMERA_MODULE_INSTALL_CONTRACT);const chimera_boot_module*phases=chimera_multiboot_find(CHIMERA_MODULE_INSTALL_PHASES);const chimera_boot_module*profiles=chimera_multiboot_find(CHIMERA_MODULE_INSTALL_PROFILES);if(!image&&!manifest&&!contract&&!phases&&!profiles){if(installer_phase++==0)console_write("[INST] Installer target not selected: no installer modules");chimera_sched_block();return;}switch(installer_phase++){case 0:console_write("[INST] Installer target detected");if(image)console_write("[INST] Installation image accepted");else console_write("[INST] ERROR: installation image module missing");if(manifest)console_write("[INST] Installation manifest accepted");else console_write("[INST] WARNING: installation manifest module missing");if(contract)console_write("[INST] Installer contract accepted");else console_write("[INST] WARNING: installer contract module missing");break;case 1:console_write("[INST] Installer runtime initialization");console_write("[INST] Initializing installer services in parallel");break;case 2:console_write("[INST] Hardware discovery service started");console_write("[INST] Storage discovery service started");break;case 3:if(phases)console_write("[INST] Installation phases loaded");if(profiles)console_write("[INST] Installer profiles loaded");console_write("[INST] Installer UI service initialized");break;case 4:console_write("[INST] Installer initialization complete");console_write("[INST] Waiting for the Koronos userspace installer loader");chimera_sched_block();break;default:chimera_sched_block();break;}}
static void koronos_submit_bootstrap_tasks(){int a=chimera_sched_submit(task_console,0,100);int b=chimera_sched_submit(task_modules,0,90);int c=chimera_sched_submit(task_live,0,80);int d=chimera_sched_submit(task_installer,0,80);console_write("[SCH ] Bootstrap tasks submitted");console_write("[SCH ] console/module/live/installer services registered");if(a<0||b<0||c<0||d<0)console_write("[SCH ] WARNING: bootstrap task registration incomplete");}
}
extern "C" void chimera_register_virtio_drivers(void);
extern "C" void chimera_register_display_drivers(void);
extern "C" void chimera_register_pci_generic_drivers(void);
extern "C" void koronos_boot(const koronos_boot_context*ctx){serial_init();console_write("CHIMERA II OS / KORONOS");console_write("[BOOT] Boot handoff: ");if(!ctx||ctx->magic!=KORONOS_BOOTINFO_MAGIC||ctx->version!=KORONOS_ABI_VERSION){koronos_state=0xBAD00001u;console_write("INVALID BOOT CONTEXT");return;}console_write("OK");console_write("[HW  ] Initializing hardware...");uint32_t modules=chimera_multiboot_scan(ctx->boot_info);console_write("[MB2 ] Scanned Multiboot2 modules");console_write("[MB2 ] Count: ");console_u32(modules);koronos_arch_init(ctx);const struct koronos_cpu_features*f=koronos_get_cpu_features();console_write("[CPU ] ");console_write(f->vendor);console_write("[CPU ] Logical CPUs: ");console_hex32(f->logical_cpus);console_write("[VM  ] Hypervisor detected: ");console_hex32(f->hypervisor);console_write("[SCH ] Initializing scheduler...");chimera_sched_init(f->logical_cpus);chimera_learning_init(f->logical_cpus);console_write("[IO  ] Initializing virtual I/O drivers...");chimera_register_virtio_drivers();chimera_register_display_drivers();chimera_register_pci_generic_drivers();
chimera_hardware_profile hw{}; if(chimera_hardware_probe(&hw)==0){console_write("[HW  ] Architecture profile ready");console_write("[HW  ] Native N-bit mode: ");console_u32(hw.native_nbit_mode);console_write("[HW  ] Best N-bit mode: ");console_u32(hw.best_nbit_mode);}
chimera_firmware_profile fw{}; if(chimera_firmware_probe(ctx,&fw)==0){console_write("[FW  ] Firmware: ");console_write(fw.type==CHIMERA_FW_UEFI?"UEFI":fw.type==CHIMERA_FW_BIOS?"BIOS":"UNKNOWN");console_write("[FW  ] ACPI present: ");console_write(fw.acpi_rsdp?"yes":"no");console_write("[FW  ] SMBIOS present: ");console_write(fw.smbios_entry?"yes":"no");console_write("[FW  ] UEFI system table: ");console_write(fw.efi_system_table?"present":"absent");}
chimera_device_inventory inv{}; int devices=chimera_hardware_enumerate_devices(&inv); console_write("[PCI ] Enumerated devices: "); console_u32(devices<0?0:(uint32_t)devices);
int bound=chimera_driver_probe_all(); console_write("[DRV ] Native/compatible bindings: "); console_u32(bound);
chimera_learning_record(1,f->logical_cpus);koronos_elf64_init();koronos_module_init();koronos_state=0x4B4F524Fu;console_write("[KRN ] KORONOS READY");console_write("[IO  ] Console: VGA text + COM1");koronos_submit_bootstrap_tasks();console_write("[RUN ] Starting cooperative scheduler runtime...");console_write("[RUN ] Scheduler now has runnable bootstrap tasks");}
