cmake_minimum_required(VERSION 3.16)
add_executable(chimera-dis chimera_tool.cpp)
add_executable(chimera-as chimera-as.cpp)
add_executable(chimera-re chimera-re.cpp)
target_compile_features(chimera-dis PRIVATE cxx_std_20)
target_compile_features(chimera-as PRIVATE cxx_std_20)
target_compile_features(chimera-re PRIVATE cxx_std_20)
install(TARGETS chimera-dis chimera-as chimera-re RUNTIME DESTINATION bin)
install(FILES chimera_isa.json README.md DESTINATION share/chimera/tools/chimera-asm)
