# Chimera II Command Compatibility Framework

CHIMERA_MODE=native

# Valid values:
#
# native
# linux
# posix
# bash
# zsh
# macos
# windows
# cmd
# powershell
#
# Explicit mode has priority over automatic detection.

AUTO_DETECT=1

LINUX_RUNTIME=
MACOS_RUNTIME=
WINDOWS_RUNTIME=
POWERSHELL_RUNTIME=
CMD_RUNTIME=
