ISA_TARGETS = [
    {'name': 'chimera-r8192', 'family': 'Chimera', 'width': 8192, 'execution': 'native'},
    {'name': 'chimera-c8192', 'family': 'Chimera', 'width': 8192, 'execution': 'native'},
    {'name': 'x86-64', 'family': 'x86', 'width': 64, 'execution': 'translated'},
    {'name': 'aarch64', 'family': 'ARM', 'width': 64, 'execution': 'translated'},
    {'name': 'riscv64', 'family': 'RISC-V', 'width': 64, 'execution': 'translated'},
    {'name': 'power64', 'family': 'POWER', 'width': 64, 'execution': 'translated'},
    {'name': 'mips64', 'family': 'MIPS', 'width': 64, 'execution': 'translated'},
    {'name': 'sparc64', 'family': 'SPARC', 'width': 64, 'execution': 'translated'},
    {'name': 's390x', 'family': 'IBM Z', 'width': 64, 'execution': 'translated'},
    {'name': 'm68k', 'family': 'Motorola 68k', 'width': 32, 'execution': 'emulated'},
    {'name': 'alpha', 'family': 'DEC Alpha', 'width': 64, 'execution': 'emulated'},
    {'name': 'parisc64', 'family': 'PA-RISC', 'width': 64, 'execution': 'emulated'},
    {'name': 'sh4', 'family': 'SuperH', 'width': 32, 'execution': 'emulated'},
    {'name': 'itanium', 'family': 'Itanium', 'width': 64, 'execution': 'emulated'},
    {'name': 'avr', 'family': 'AVR', 'width': 8, 'execution': 'emulated'},
    {'name': 'xtensa', 'family': 'Xtensa', 'width': 32, 'execution': 'emulated'},
    {'name': 'wasm32', 'family': 'WebAssembly', 'width': 32, 'execution': 'imported'},
]
