#!/usr/bin/env bash

# --- Chimera II OS standard help ---
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  cat <<'CHIMERA_HELP'
Chimera II OS script: boot/iso/prepare-layout.sh

Usage:
  boot/iso/prepare-layout.sh [options] [arguments]

Options:
  -h, --help    Show this help and exit successfully.

Notes:
  This help entry is provided consistently across Chimera II OS shell tools.
  The script's existing command-line interface and environment variables remain unchanged.
CHIMERA_HELP
  exit 0
fi
set -euo pipefail

chimera_copy_if_distinct() {
    local src="$1"
    local dst="$2"

    mkdir -p "$(dirname "$dst")"

    local src_real dst_real
    src_real="$(realpath -m "$src")"
    dst_real="$(realpath -m "$dst")"

    if [[ "$src_real" == "$dst_real" ]]; then
        echo "[CHIMERA] SKIP self-copy: $src_real"
        return 0
    fi

    cp -f -- "$src" "$dst"
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIST="$ROOT/boot/iso/dist/iso"
rm -rf "$DIST"
mkdir -p "$DIST/boot/grub" "$DIST/boot/jasper" "$DIST/boot/spitfire" "$DIST/boot/koronos" "$DIST/EFI/BOOT" "$DIST/EFI/CHIMERA"
mkdir -p "$DIST/boot/chimera/elf" "$DIST/boot/chimera/bin" "$DIST/boot/chimera/manifests" "$DIST/boot/chimera/spitfire" "$DIST/boot/chimera/jasper" "$DIST/boot/chimera/grub"

# Stage every runtime boot artifact generated by the build pipeline.
if [[ -f "$ROOT/tools/build-boot-artifacts.sh" ]]; then bash "$ROOT/tools/build-boot-artifacts.sh"; fi
BOOT_ART="$ROOT/build/boot-artifacts"
if [[ -d "$BOOT_ART/all-elf" ]]; then cp -a "$BOOT_ART/all-elf/." "$DIST/boot/chimera/elf/"; fi
if [[ -d "$BOOT_ART/runtime" ]]; then cp -a "$BOOT_ART/runtime/." "$DIST/boot/chimera/elf/"; fi
if [[ -d "$BOOT_ART/all-bin" ]]; then cp -a "$BOOT_ART/all-bin/." "$DIST/boot/chimera/bin/"; fi
if [[ -d "$BOOT_ART/spitfire" ]]; then cp -a "$BOOT_ART/spitfire/." "$DIST/boot/chimera/spitfire/"; fi
if [[ -d "$BOOT_ART/jasper" ]]; then cp -a "$BOOT_ART/jasper/." "$DIST/boot/chimera/jasper/"; fi
if [[ -d "$BOOT_ART/grub" ]]; then cp -a "$BOOT_ART/grub/." "$DIST/boot/chimera/grub/"; fi
if [[ -d "$BOOT_ART/manifests" ]]; then cp -a "$BOOT_ART/manifests/." "$DIST/boot/chimera/manifests/"; fi
mkdir -p "$DIST/chimera/manifests" "$DIST/chimera/docs" "$DIST/src" "$DIST/usr/share/chimera/aurora" "$DIST/install" "$DIST/checksums"

# Hard-stage canonical boot artwork and Init.mp4 so every boot policy layer can access
# the same offline assets without depending on network access or a desktop session.
mkdir -p "$DIST/boot/visual" "$DIST/usr/share/chimera/aurora/assets" "$DIST/desktop/aurora"
cp -f "$ROOT/boot/splash/spitfire_background.svg" "$DIST/boot/visual/spitfire_background.svg"
cp -f "$ROOT/boot/splash/jasper_background.svg" "$DIST/boot/visual/jasper_background.svg"
cp -f "$ROOT/boot/splash/aurora_boot_splash.svg" "$DIST/boot/visual/aurora_boot_splash.svg"
# Materialize the canonical offline Aurora JPEG for legacy GRUB/Jasper contracts.
if command -v base64 >/dev/null 2>&1; then
  base64 -d "$ROOT/boot/visual/aurora-wayland-glass.jpg.b64" > "$DIST/boot/visual/aurora-wayland-glass.jpg"
else
  python3 - "$ROOT/boot/visual/aurora-wayland-glass.jpg.b64" "$DIST/boot/visual/aurora-wayland-glass.jpg" <<'PY'
import base64, pathlib, sys
pathlib.Path(sys.argv[2]).write_bytes(base64.b64decode(pathlib.Path(sys.argv[1]).read_text()))
PY
fi
[[ "$(head -c 3 "$DIST/boot/visual/aurora-wayland-glass.jpg" | od -An -tx1 | tr -d ' 
')" == "ffd8ff" ]] || { echo "Aurora JPEG artwork decode failed." >&2; exit 2; }
cp -f "$ROOT/desktop/aurora/assets/Init.mp4" "$DIST/boot/visual/Init.mp4"
cp -f "$ROOT/desktop/aurora/assets/Init.mp4" "$DIST/usr/share/chimera/aurora/assets/Init.mp4"
install -m 0755 "$ROOT/desktop/aurora/aurora-progress.sh" "$DIST/usr/share/chimera/aurora-progress.sh"
cp -f "$ROOT/desktop/aurora/assets/Init.mp4" "$DIST/desktop/aurora/Init.mp4"
[[ -s "$DIST/boot/visual/Init.mp4" ]] || { echo "Init.mp4 boot asset missing." >&2; exit 2; }

# Compatibility layout required by the ISO contract.  The source tree is kept
# as a compressed archive under /src so the ISO remains source-first without
# expanding thousands of source files into the ISO root.
SOURCE_ARCHIVE="$DIST/src/chimera-source.tar.zst"
if command -v zstd >/dev/null 2>&1; then
  tar -C "$ROOT" \
    --exclude=.git --exclude=build --exclude=boot/iso/dist --exclude=boot/iso/work \
    --exclude='*.iso' --exclude='*.img' --exclude='*.o' --exclude='*.a' \
    --exclude='node_modules' --exclude='__pycache__' \
    -cf - . | zstd -T0 -q -o "$SOURCE_ARCHIVE"
elif command -v gzip >/dev/null 2>&1; then
  SOURCE_ARCHIVE="$DIST/src/chimera-source.tar.gz"
  tar -C "$ROOT" \
    --exclude=.git --exclude=build --exclude=boot/iso/dist --exclude=boot/iso/work \
    --exclude='*.iso' --exclude='*.img' --exclude='*.o' --exclude='*.a' \
    --exclude='node_modules' --exclude='__pycache__' \
    -czf "$SOURCE_ARCHIVE" .
else
  echo "Neither zstd nor gzip is available for the source archive." >&2
  exit 2
fi
cat > "$DIST/src/README.txt" <<'EOF'
Chimera II OS source archive
============================
The source-first ISO stores the repository source in compressed form under
/src/chimera-source.tar.zst (or chimera-source.tar.gz when zstd is unavailable).
The archive excludes the Git metadata and generated build/output trees.
EOF

# Build and stage the live-boot payload explicitly. Jasper/GRUB references
# /boot/live/chimera-live-initramfs.img and /boot/live/live-manifest.json;
# relying on an optional pre-existing build/live-boot directory caused
# boot-time "file not found" failures.
if [[ -x "$ROOT/tools/build-live-boot-binaries.sh" ]]; then
  bash "$ROOT/tools/build-live-boot-binaries.sh"
else
  echo "Live boot builder missing: $ROOT/tools/build-live-boot-binaries.sh" >&2
  exit 2
fi
LIVE_BOOT="$ROOT/build/live-boot"
for required in \
  "$LIVE_BOOT/boot/live/chimera-live-initramfs.img" \
  "$LIVE_BOOT/boot/live/live-manifest.json"; do
  [[ -s "$required" ]] || { echo "Required live artifact missing: $required" >&2; exit 2; }
done
mkdir -p "$DIST/boot/live"
cp -f "$LIVE_BOOT/boot/live/chimera-live-initramfs.img" "$DIST/boot/live/"
cp -f "$LIVE_BOOT/boot/live/live-manifest.json" "$DIST/boot/live/"
if [[ -s "$LIVE_BOOT/boot/vmlinuz" ]]; then
  cp -f "$LIVE_BOOT/boot/vmlinuz" "$DIST/boot/live/vmlinuz"
fi

# Canonical kernel payload: the exact ELF validated by grub-file and loaded by GRUB's multiboot2 command.
KERNEL="$ROOT/build/koronos/x86_64/koronos.elf"
[[ -s "$KERNEL" ]] || { echo "Koronos kernel ELF missing: $KERNEL" >&2; exit 1; }
chimera_copy_if_distinct "$KERNEL" "$DIST/boot/koronos/koronos.elf"

# Bootloader source/artifacts and Jasper recovery configuration.
cp "$ROOT/boot/spitfire/sf0_mbr.asm" "$ROOT/boot/spitfire/sf1_longmode.asm" "$ROOT/boot/spitfire/sf2_loader.cpp" "$ROOT/boot/spitfire/sf2_loader.h" "$ROOT/boot/spitfire/spitfire.ld" "$DIST/boot/spitfire/"
cp "$ROOT/boot/spitfire/sfu_uefi.c" "$ROOT/boot/spitfire/sfu_uefi.h" "$ROOT/boot/spitfire/sfu_uefi.ld" "$DIST/EFI/CHIMERA/"
cp "$ROOT/boot/iso/grub.cfg" "$DIST/boot/grub/grub.cfg"
cp "$ROOT/boot/jasper/jasper.cfg" "$DIST/boot/jasper/jasper.cfg"
# Legacy Jasper contract: older installers and recovery tooling look for
# /boot/jasper/grub.cfg. Keep it synchronized with the canonical GRUB entry.
cp "$ROOT/boot/iso/grub.cfg" "$DIST/boot/jasper/grub.cfg"
[[ -s "$BOOT_ART/jasper/jasper.elf" ]] || { echo "Jasper ELF missing from boot artifact stage." >&2; exit 2; }
cp "$BOOT_ART/jasper/jasper.elf" "$DIST/boot/jasper/jasper.elf"
if [[ -s "$BOOT_ART/grub/grub-core.img" ]]; then cp "$BOOT_ART/grub/grub-core.img" "$DIST/boot/chimera/grub/grub-core.img"; fi
cp "$ROOT/boot/jasper/live.cfg" "$DIST/boot/jasper/live.cfg"
cp "$ROOT/boot/jasper/install.cfg" "$DIST/boot/jasper/install.cfg"
cp "$ROOT/boot/jasper/diagnostics.cfg" "$DIST/boot/jasper/diagnostics.cfg"
cp "$ROOT/boot/spitfire/spitfire-menu.cfg" "$DIST/boot/spitfire/spitfire-menu.cfg"
mkdir -p "$DIST/boot/installation" "$DIST/boot/recovery" "$DIST/boot/diagnostics"
cp "$ROOT/boot/installation/menu.cfg" "$DIST/boot/installation/menu.cfg"
cp "$ROOT/boot/recovery/recovery-manifest.json" "$DIST/boot/recovery/recovery-manifest.json"
cp "$ROOT/boot/diagnostics/diagnostics-manifest.json" "$DIST/boot/diagnostics/diagnostics-manifest.json"
cp "$ROOT/boot/boot-menu-contract.json" "$DIST/boot/boot-menu-contract.json"
cp "$ROOT/boot/livecd/live-manifest.json" "$DIST/boot/live-manifest.json"
if [[ -d "$ROOT/build/live-boot/boot/live" ]]; then cp -a "$ROOT/build/live-boot/boot/live" "$DIST/boot/"; fi

cat > "$DIST/boot/jasper/recovery.cfg" <<'EOF'
set timeout=5
set default=0
insmod normal
insmod gfxterm
insmod png
insmod search
if [ -f /boot/jasper/background.png ]; then background_image /boot/jasper/background.png; fi
menuentry "Jasper Recovery — Koronos Rescue" { multiboot2 /boot/koronos/koronos.elf
  module2 /boot/recovery/recovery-manifest.json chimera-recovery-manifest }
menuentry "Jasper Recovery — Safe Graphics" { multiboot2 /boot/koronos/koronos.elf }
menuentry "Jasper Recovery — GRUB Command Line" { commandline }
menuentry "Jasper Recovery — Reboot" { reboot }
menuentry "Jasper Recovery — Power Off" { halt }
EOF

[[ -f "$ROOT/boot/boot_protocol.json" ]] && cp "$ROOT/boot/boot_protocol.json" "$DIST/boot/"
[[ -f "$ROOT/boot/startup/boot_phase_manifest.json" ]] && cp "$ROOT/boot/startup/boot_phase_manifest.json" "$DIST/boot/"

# Aurora source artwork is kept in the ISO; raster PNGs are generated for GRUB and installer windows.
RASTERIZER=""
if command -v rsvg-convert >/dev/null 2>&1; then RASTERIZER=rsvg-convert
elif command -v convert >/dev/null 2>&1; then RASTERIZER=convert
else echo "Aurora artwork requires rsvg-convert or ImageMagick." >&2; exit 2
fi

if [[ "$RASTERIZER" == "rsvg-convert" ]]; then
  rsvg-convert -w 1920 -h 1080 "$ROOT/desktop/aurora/assets/aurora-wayland-glass.svg" -o "$DIST/boot/grub/aurora-wayland-glass.png"
  rsvg-convert -w 1920 -h 1080 "$ROOT/desktop/aurora/assets/aurora-installer.svg" -o "$DIST/install/installer-background.png"
  rsvg-convert -w 1920 -h 1080 "$ROOT/desktop/aurora/assets/aurora-library.svg" -o "$DIST/usr/share/chimera/aurora/library-background.png"
  rsvg-convert -w 1920 -h 1080 "$ROOT/desktop/aurora/assets/aurora-desktop.svg" -o "$DIST/usr/share/chimera/aurora/desktop-background.png"
  rsvg-convert -w 1920 -h 1080 "$ROOT/boot/splash/jasper_background.svg" -o "$DIST/boot/jasper/background.png"
  rsvg-convert -w 1920 -h 1080 "$ROOT/boot/splash/spitfire_background.svg" -o "$DIST/boot/spitfire/background.png"
else
  convert -background none "$ROOT/desktop/aurora/assets/aurora-wayland-glass.svg" "$DIST/boot/grub/aurora-wayland-glass.png"
  convert -background none "$ROOT/desktop/aurora/assets/aurora-installer.svg" "$DIST/install/installer-background.png"
  convert -background none "$ROOT/desktop/aurora/assets/aurora-library.svg" "$DIST/usr/share/chimera/aurora/library-background.png"
  convert -background none "$ROOT/desktop/aurora/assets/aurora-desktop.svg" "$DIST/usr/share/chimera/aurora/desktop-background.png"
  convert -background none "$ROOT/boot/splash/jasper_background.svg" "$DIST/boot/jasper/background.png"
  convert -background none "$ROOT/boot/splash/spitfire_background.svg" "$DIST/boot/spitfire/background.png"
fi
cp "$ROOT/desktop/aurora/assets/aurora-wayland-glass.svg" "$ROOT/desktop/aurora/assets/aurora-installer.svg" "$ROOT/desktop/aurora/assets/aurora-library.svg" "$ROOT/desktop/aurora/assets/aurora-desktop.svg" "$DIST/usr/share/chimera/aurora/"

# Installer/desktop background manifest gives every installer window a deterministic visual asset.
cat > "$DIST/install/background-manifest.json" <<'EOF'
{
  "schema": "CHM-INSTALL-BACKGROUNDS-1",
  "default": "/install/installer-background.png",
  "steps": {
    "welcome": "/install/installer-background.png",
    "hardware": "/usr/share/chimera/aurora/library-background.png",
    "mode": "/usr/share/chimera/aurora/desktop-background.png",
    "target": "/usr/share/chimera/aurora/desktop-background.png",
    "storage": "/usr/share/chimera/aurora/desktop-background.png",
    "boot": "/boot/spitfire/background.png",
    "software": "/usr/share/chimera/aurora/library-background.png",
    "security": "/boot/jasper/background.png",
    "tools": "/usr/share/chimera/aurora/library-background.png",
    "users": "/usr/share/chimera/aurora/desktop-background.png",
    "install": "/install/installer-background.png",
    "validate": "/boot/jasper/background.png",
    "reboot": "/boot/grub/aurora-wayland-glass.png"
  }
}
EOF

[[ -f "$ROOT/installer/installation_phases.json" ]] && cp "$ROOT/installer/installation_phases.json" "$DIST/chimera/manifests/"
[[ -f "$ROOT/installer/installer_profiles.json" ]] && cp "$ROOT/installer/installer_profiles.json" "$DIST/chimera/manifests/"
[[ -f "$ROOT/installer/chimera-installer-plan.json" ]] && cp "$ROOT/installer/chimera-installer-plan.json" "$DIST/chimera/manifests/"
[[ -f "$ROOT/README.md" ]] && cp "$ROOT/README.md" "$DIST/chimera/docs/README.md"
cat > "$DIST/chimera/README.txt" <<'EOF'
Chimera II OS ISO
=================
This media contains the Koronos kernel, Spit Fire/Jasper boot chain,
Aurora graphical resources, live boot environment, installer contracts,
and the compressed source archive under /src.

The canonical project documentation is staged as /chimera/docs/README.md.
EOF

python3 "$ROOT/boot/iso/validate-iso.py" --tree "$DIST" --write-manifest "$DIST/checksums/SHA256SUMS"
