#!/usr/bin/env bash

# --- Chimera II OS standard help ---
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  cat <<'CHIMERA_HELP'
Chimera II OS script: tools/branding/chimera-set-desktop-background.sh

Usage:
  tools/branding/chimera-set-desktop-background.sh [options] [arguments]

Options:
  -h, --help    Show this help and exit successfully.

Notes:
  This help entry is provided consistently across Chimera II OS shell tools.
  The script's existing command-line interface and environment variables remain unchanged.
CHIMERA_HELP
  exit 0
fi
set -Eeuo pipefail

# Change Chimera II OS Aurora desktop/lockscreen background without rebuilding
# the ISO. This changes the runtime configuration and installs the selected
# image under the canonical Chimera background directory.
ROOT="$CHIMERA_ROOTFS"
[[ -n "$ROOT" ]] || ROOT=/
CONFIG="$ROOT/etc/chimera/desktop-background.conf"
TARGET_DIR="$ROOT/usr/share/backgrounds/chimera"
IMAGE="${1-}"

if [[ -z "$IMAGE" || ! -f "$IMAGE" ]]; then
  echo "Usage: $0 /path/to/background.png" >&2
  exit 2
fi

mkdir -p "$TARGET_DIR" "$(dirname "$CONFIG")"
install -m 0644 "$IMAGE" "$TARGET_DIR/custom-background.png"

cat > "$CONFIG" <<EOF
# Generated by chimera-set-desktop-background.
CHIMERA_DESKTOP_BACKGROUND=/usr/share/backgrounds/chimera/custom-background.png
CHIMERA_LOCKSCREEN_BACKGROUND=/usr/share/backgrounds/chimera/custom-background.png
EOF

echo "Chimera desktop background updated: $TARGET_DIR/custom-background.png"
echo "Restart/reload the Aurora compositor or desktop session to apply it."
