#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ISO="${CHIMERA_ISO:-$ROOT/build/iso/chimera-ii-os.iso}"
VMX="${CHIMERA_VMX:-$ROOT/build/vmware/chimera-ii-os.vmx}"
DISK="${CHIMERA_VMDK:-$ROOT/build/vmware/chimera-ii-os.vmdk}"
MEM="${CHIMERA_VM_MEMORY_MB:-4096}"
CPUS="${CHIMERA_VM_CPUS:-2}"
mkdir -p "$(dirname "$VMX")"
cat >"$VMX" <<EOF
.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "20"
memsize = "$MEM"
numvcpus = "$CPUS"
guestOS = "otherlinux-64"
firmware = "efi"
sata0.present = "TRUE"
sata0:0.present = "TRUE"
sata0:0.fileName = "chimera-ii-os.vmdk"
sata0:1.present = "TRUE"
sata0:1.deviceType = "cdrom-image"
sata0:1.fileName = "$ISO"
ethernet0.present = "TRUE"
ethernet0.virtualDev = "vmxnet3"
ethernet0.connectionType = "nat"
usb.present = "TRUE"
usb_xhci.present = "TRUE"
svga.present = "TRUE"
svga.vramSize = "134217728"
chipset.useAcpi = "TRUE"
EOF
if command -v vmware-vdiskmanager >/dev/null 2>&1 && [[ ! -e "$DISK" ]]; then vmware-vdiskmanager -c -s 32G -a lsilogic -t 0 "$DISK"; fi
printf '%s\n' "Generated VMware UEFI VMX: $VMX"
printf '%s\n' "Firmware: EFI; NIC: vmxnet3; USB: xHCI; graphics: SVGA"
