#include "chimera.h"
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
static void build_graph(ChimeraBrain *b){b->edge_count=0;for(uint32_t i=0;i<b->node_count&&b->edge_count<CHIMERA_MAX_EDGES;++i){uint32_t j=(i+1U)%b->node_count;b->edges[b->edge_count++]=(ChimeraEdge){(uint16_t)i,(uint16_t)j,0};if(b->node_count>2&&b->edge_count<CHIMERA_MAX_EDGES){uint32_t k=(i+2U)%b->node_count;b->edges[b->edge_count++]=(ChimeraEdge){(uint16_t)i,(uint16_t)k,0};}}}
int chimera_init(ChimeraState*s,uint32_t cpu_count,uint32_t node_count){if(!s||cpu_count==0||cpu_count>CHIMERA_MAX_CPUS||node_count==0||node_count>CHIMERA_MAX_NODES)return-1;memset(s,0,sizeof(*s));if(pthread_mutex_init(&s->lock,NULL)!=0)return-1;s->cpu_count=cpu_count;s->brain.node_count=node_count;s->run_state=CHIMERA_PAUSED;for(uint32_t i=0;i<cpu_count;++i)s->cpus[i].id=i;build_graph(&s->brain);return 0;}
void chimera_destroy(ChimeraState*s){if(s)pthread_mutex_destroy(&s->lock);}
void chimera_reset(ChimeraState*s){if(!s)return;pthread_mutex_lock(&s->lock);uint32_t n=s->cpu_count,nodes=s->brain.node_count;memset(s->cpus,0,sizeof(s->cpus));memset(s->memory,0,sizeof(s->memory));memset(&s->brain,0,sizeof(s->brain));s->brain.node_count=nodes;build_graph(&s->brain);s->cpu_count=n;s->ticks=0;s->messages_sent=0;s->messages_delivered=0;s->scheduler_cursor=0;for(uint32_t i=0;i<n;++i)s->cpus[i].id=i;s->run_state=CHIMERA_PAUSED;pthread_mutex_unlock(&s->lock);}
int chimera_step(ChimeraState*s){if(!s)return-1;pthread_mutex_lock(&s->lock);uint32_t id=s->scheduler_cursor%s->cpu_count;ChimeraCPU*cpu=&s->cpus[id];if(!cpu->halted){cpu->pc+=4;cpu->instructions++;cpu->regs[0].bytes[0]=(uint8_t)(cpu->instructions&0xffU);s->memory[cpu->pc%CHIMERA_MEMORY_SIZE]=(uint8_t)cpu->instructions;s->messages_sent++;s->messages_delivered++;uint32_t node=id%s->brain.node_count;s->brain.activity[node]++;for(uint32_t e=0;e<s->brain.edge_count;++e)if(s->brain.edges[e].from==node){s->brain.edges[e].packets++;break;}}s->scheduler_cursor=(id+1U)%s->cpu_count;s->ticks++;pthread_mutex_unlock(&s->lock);return 0;}
int chimera_control(ChimeraState*s,const char*action){if(!s||!action)return-1;if(strcmp(action,"start")==0){pthread_mutex_lock(&s->lock);s->run_state=CHIMERA_RUNNING;pthread_mutex_unlock(&s->lock);return 0;}if(strcmp(action,"pause")==0){pthread_mutex_lock(&s->lock);s->run_state=CHIMERA_PAUSED;pthread_mutex_unlock(&s->lock);return 0;}if(strcmp(action,"step")==0)return chimera_step(s);if(strcmp(action,"reset")==0){chimera_reset(s);return 0;}return-1;}
static int append(char**p,size_t*left,const char*fmt,...){va_list ap;va_start(ap,fmt);int n=vsnprintf(*p,*left,fmt,ap);va_end(ap);if(n<0||(size_t)n>=*left)return-1;*p+=n;*left-=(size_t)n;return 0;}
int chimera_state_json(ChimeraState*s,char*out,size_t cap){if(!s||!out||cap<128)return-1;pthread_mutex_lock(&s->lock);char*p=out;size_t left=cap;if(append(&p,&left,"{\"ticks\":%llu,\"run_state\":%d,\"scheduler_cursor\":%u,\"messages_sent\":%llu,\"messages_delivered\":%llu,\"memory_bytes\":%u,\"register_bits\":8192,\"cpus\":[",(unsigned long long)s->ticks,(int)s->run_state,s->scheduler_cursor,(unsigned long long)s->messages_sent,(unsigned long long)s->messages_delivered,CHIMERA_MEMORY_SIZE))goto fail;for(uint32_t i=0;i<s->cpu_count;i++){if(i&&append(&p,&left,",")<0)goto fail;if(append(&p,&left,"{\"id\":%u,\"pc\":%llu,\"instructions\":%llu,\"halted\":%u,\"reg0_byte0\":%u}",s->cpus[i].id,(unsigned long long)s->cpus[i].pc,(unsigned long long)s->cpus[i].instructions,s->cpus[i].halted,s->cpus[i].regs[0].bytes[0])<0)goto fail;}if(append(&p,&left,"],\"brain\":{\"nodes\":%u,\"edges\":[",s->brain.node_count)<0)goto fail;for(uint32_t i=0;i<s->brain.edge_count;i++){if(i&&append(&p,&left,",")<0)goto fail;if(append(&p,&left,"[%u,%u,%u]",s->brain.edges[i].from,s->brain.edges[i].to,s->brain.edges[i].packets)<0)goto fail;}if(append(&p,&left,"]}}")<0)goto fail;pthread_mutex_unlock(&s->lock);return(int)(p-out);fail:pthread_mutex_unlock(&s->lock);if(cap)out[0]='\0';return-1;}
