target_sources(chimera_machine PRIVATE src/ai/runtime.cpp src/parallel/parallel.cpp src/iot/iot.cpp src/data/data.cpp src/performance/performance.cpp src/network/ai_network.cpp src/dashboard/dashboard.cpp)
add_executable(chimera_ai_runtime_test tests/ai/test_runtime.cpp)
target_link_libraries(chimera_ai_runtime_test PRIVATE chimera_machine)
target_include_directories(chimera_ai_runtime_test PRIVATE include)
add_executable(chimera_parallel_test tests/parallel/test_parallel.cpp)
target_link_libraries(chimera_parallel_test PRIVATE chimera_machine)
target_include_directories(chimera_parallel_test PRIVATE include)
add_executable(chimera_iot_test tests/iot/test_iot.cpp)
target_link_libraries(chimera_iot_test PRIVATE chimera_machine)
target_include_directories(chimera_iot_test PRIVATE include)
add_executable(chimera_data_test tests/data/test_data.cpp)
target_link_libraries(chimera_data_test PRIVATE chimera_machine)
target_include_directories(chimera_data_test PRIVATE include)
add_executable(chimera_performance_test tests/performance/test_performance.cpp)
target_link_libraries(chimera_performance_test PRIVATE chimera_machine)
target_include_directories(chimera_performance_test PRIVATE include)
add_executable(chimera_ai_network_test tests/network/test_ai_network.cpp)
target_link_libraries(chimera_ai_network_test PRIVATE chimera_machine)
target_include_directories(chimera_ai_network_test PRIVATE include)
add_executable(chimera_dashboard_test tests/dashboard/test_dashboard.cpp)
target_link_libraries(chimera_dashboard_test PRIVATE chimera_machine)
target_include_directories(chimera_dashboard_test PRIVATE include)
add_test(NAME chimera_ai_runtime COMMAND chimera_ai_runtime_test)
add_test(NAME chimera_parallel COMMAND chimera_parallel_test)
add_test(NAME chimera_iot COMMAND chimera_iot_test)
add_test(NAME chimera_data COMMAND chimera_data_test)
add_test(NAME chimera_performance COMMAND chimera_performance_test)
add_test(NAME chimera_ai_network COMMAND chimera_ai_network_test)
add_test(NAME chimera_dashboard COMMAND chimera_dashboard_test)
install(FILES ai/nextgen/algorithms.json ai/nextgen/algorithms_2026.json ai/nextgen/hardware.json ai/nextgen/iot_protocols.json docs/ai/nextgen-2026.md DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/ai)
install(FILES data/registry/databases.json data/registry/hadoop.json data/registry/openstack.json data/registry/licenses.json data/hadoop/hadoop_profile.json data/openstack/openstack_profile.json performance/registry/performance_profiles.json performance/registry/repair_policies.json performance/registry/scaffolds.json network/protocols/ai_network_protocols.json network/protocols/routing_protocols.json network/protocols/edition_network_profiles.json dashboard/kpis.json DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/data)
install(FILES data/network/gateways.json data/network/chimera_nodes.json data/network/discovered_hosts.json data/network/peers.json desktop/aurora/network_fabric.json DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/network)
install(FILES dashboard/kpis.json dashboard/edition_profiles.json desktop/aurora/dashboard.json DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/dashboard)
install(FILES installer/installer_profiles.json include/chimera/ai/runtime.h include/chimera/parallel/parallel.h include/chimera/iot/iot.h include/chimera/data/data.h include/chimera/performance/performance.h include/chimera/network/ai_network.h include/chimera/dashboard/dashboard.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/chimera)
install(PROGRAMS tools/ai/chimera_ai_runtime.py tools/parallel/chimera_parallel.py tools/iot/chimera_iot.py tools/data/chimera_data.py tools/data/hadoop_doctor.py tools/data/openstack_doctor.py tools/repair/chimera_repair.py tools/scaffold/chimera_scaffold.py tools/network/chimera_browser.py tools/security/chimera_sentinel.py tools/dashboard/chimera_dashboard.py installer/chimera_installer.py tools/build/build_all_editions.py package/chimera_pkg.py DESTINATION ${CMAKE_INSTALL_BINDIR})
install(DIRECTORY package/providers DESTINATION ${CMAKE_INSTALL_BINDIR})
install(FILES installer/install-chimera.bat installer/install-chimera.ps1 installer/install-chimera.sh tools/build/build_all_editions.bat tools/build/build_all_editions.ps1 tools/build/build_all_editions.sh DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/scripts)
