target_sources(chimera_machine PRIVATE src/ai/runtime.cpp src/parallel/parallel.cpp src/iot/iot.cpp src/data/data.cpp)
add_executable(chimera_ai_runtime_test tests/ai/test_runtime.cpp)
target_link_libraries(chimera_ai_runtime_test PRIVATE chimera_machine)
target_include_directories(chimera_ai_runtime_test PRIVATE include)
add_executable(chimera_parallel_test tests/parallel/test_parallel.cpp)
target_link_libraries(chimera_parallel_test PRIVATE chimera_machine)
target_include_directories(chimera_parallel_test PRIVATE include)
add_executable(chimera_iot_test tests/iot/test_iot.cpp)
target_link_libraries(chimera_iot_test PRIVATE chimera_machine)
target_include_directories(chimera_iot_test PRIVATE include)
add_executable(chimera_data_test tests/data/test_data.cpp)
target_link_libraries(chimera_data_test PRIVATE chimera_machine)
target_include_directories(chimera_data_test PRIVATE include)
add_test(NAME chimera_ai_runtime COMMAND chimera_ai_runtime_test)
add_test(NAME chimera_parallel COMMAND chimera_parallel_test)
add_test(NAME chimera_iot COMMAND chimera_iot_test)
add_test(NAME chimera_data COMMAND chimera_data_test)
install(FILES ai/nextgen/algorithms.json ai/nextgen/algorithms_2026.json ai/nextgen/hardware.json ai/nextgen/iot_protocols.json docs/ai/nextgen-2026.md DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/ai)
install(FILES data/registry/databases.json data/registry/hadoop.json data/registry/openstack.json DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/data)
install(FILES include/chimera/ai/runtime.h include/chimera/parallel/parallel.h include/chimera/iot/iot.h include/chimera/data/data.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/chimera)
install(PROGRAMS tools/ai/chimera_ai_runtime.py tools/parallel/chimera_parallel.py tools/iot/chimera_iot.py tools/data/chimera_data.py package/chimera_pkg.py DESTINATION ${CMAKE_INSTALL_BINDIR})
install(DIRECTORY package/providers DESTINATION ${CMAKE_INSTALL_DATADIR}/chimera/package)
