Texture2D InputTex;
SamplerState InputSampler;

float2 InvSize;
float4 PS_Blur(float2 UV : TEXCOORD0) : SV_Target0
{
    const float weights[5] = {0.227027f, 0.1945946f, 0.1216216f, 0.054054f, 0.016216f};
    float4 sum = InputTex.Sample(InputSampler, UV) * weights[0];
    [unroll]
    for (int i = 1; i < 5; ++i)
    {
        float2 d = InvSize * float(i);
        sum += InputTex.Sample(InputSampler, UV + d) * weights[i];
        sum += InputTex.Sample(InputSampler, UV - d) * weights[i];
    }
    return sum;
}
