(()=>{'use strict';const BRIDGE='http://127.0.0.1:8766';let image=null,stopped=false;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function setProgress(v,msg){$('#ocrProgress span').style.width=Math.max(0,Math.min(100,v))+'%';$('#ocrStatus').textContent=msg||('OCR '+Math.round(v)+'%')}
function dataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function draw(){const c=$('#ocrCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!image)return;const s=Math.min(c.width/image.width,c.height/image.height),x=(c.width-image.width*s)/2,y=(c.height-image.height*s)/2;ctx.drawImage(image,x,y,image.width*s,image.height*s)}
async function bridge(path,body){const r=await fetch(BRIDGE+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json()}
async function browserOCR(src,script){if(!window.Tesseract)throw Error('Tesseract.js failed to load');const map={auto:'grc','ancient-greek':'grc',greek:'ell',syriac:'syr',arabic:'ara',hebrew:'heb',coptic:'cop',latin:'lat'};const code=map[script]||'grc';setProgress(12,'Loading browser OCR model: '+code);const w=await Tesseract.createWorker(code);try{const r=await w.recognize(src,{rotateAuto:true},{text:true});return{ok:true,engine:'tesseract.js',language:code,text:r.data.text||'',confidence:r.data.confidence||0,automatic:script==='auto'}}finally{await w.terminate()}}
async function scan(){if(!image){$('#ocrResults').textContent='Choose an image first.';return}stopped=false;$('#ocrResults').textContent='Scanning…';$('#ocrDiagnostics').innerHTML='';setProgress(3,'Preparing image');const file=$('#ocrFile').files[0],src=await dataUrl(file),script=$('#ocrScript').value,psm=Number($('#ocrPsm').value);
if(script==='thamudic'){try{const r=await bridge('/thamudic/ocr',{image:src,width:image.width,height:image.height,threshold:128});$('#ocrEngine').innerHTML='<span>Thamudic vision</span><span>'+esc(r.modelAvailable?'reviewed local model':'automatic segmentation')+'</span>';$('#ocrResults').innerHTML='<strong>Automatic segmentation completed.</strong><pre>'+esc(JSON.stringify(r.boxes||[],null,2))+'</pre>';$('#ocrDiagnostics').innerHTML='<span>U+10A80–U+10A9F</span><span>'+esc(r.modelAvailable?'reviewed local model available':'no standard Tesseract model')+'</span><span>Human review required</span>';setProgress(100,'Thamudic scan complete');return}catch(e){}}
try{setProgress(10,'Trying local OCR bridge');const local=await bridge('/ocr/scan',{image:src,language:script,script,psm});if(local.ok){$('#ocrEngine').innerHTML='<span>Local Tesseract</span><span>'+esc(local.language||'auto')+'</span>';$('#ocrResults').innerHTML='<pre>'+esc(local.text||'(no text recognized)')+'</pre>';$('#ocrDiagnostics').innerHTML='<span>Language '+esc(local.language||'auto')+'</span><span>Automatic: '+(local.automatic?'yes':'no')+'</span>';setProgress(100,'OCR complete · local engine');return}}catch(e){$('#ocrDiagnostics').innerHTML='<span>Local bridge unavailable · browser fallback</span>'}
if(stopped)return;try{const r=await browserOCR(src,script);$('#ocrEngine').innerHTML='<span>Browser WebAssembly</span><span>'+esc(r.language)+'</span>';$('#ocrResults').innerHTML='<pre>'+esc(r.text||'(no text recognized)')+'</pre>';$('#ocrDiagnostics').innerHTML='<span>Confidence '+esc(r.confidence||0)+'%</span><span>Source image retained locally</span>';setProgress(100,'OCR complete · browser engine')}catch(e){$('#ocrResults').innerHTML='<strong>OCR could not start.</strong><p>'+esc(e.message)+'</p><p>Start tools/thamudic-nlp/bridge.py for local OCR, or allow the Tesseract.js CDN.</p>';setProgress(0,'OCR unavailable')}}
$('#ocrFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f);image=new Image();image.onload=()=>{draw();URL.revokeObjectURL(u);if($('#ocrAuto').value==='on')scan()};image.src=u};
$('#ocrScan').onclick=scan;$('#ocrStop').onclick=()=>{stopped=true;setProgress(0,'OCR stopped')};$('#ocrCopy').onclick=()=>navigator.clipboard?.writeText($('#ocrResults').innerText||'');
(async()=>{try{const r=await bridge('/health');$('#ocrStatus').textContent='OCR bridge: '+(r.ocr?'online':'segmentation-only')+' · '+(r.tesseractLanguages||[]).join(', ');$('#ocrDiagnostics').innerHTML='<span>Local engine detected</span><span>'+esc((r.tesseractLanguages||[]).join(', ')||'No Tesseract language packs')+'</span>'}catch{$('#ocrStatus').textContent='OCR bridge offline · browser fallback ready';$('#ocrDiagnostics').innerHTML='<span>Browser fallback ready</span>'}})()})();