const apps=[
{id:"bizx",name:"BizX",repo:"amerhwitat/BizX",cat:"Games & Business",local:true,desc:"Business simulation, RPG/strategy, networking, wallets, rendering and cross-language game systems.",tags:["WebGL","Three.js","Unity","Unreal","NetworkUnified"],url:"https://github.com/amerhwitat/BizX",portal:"game-center.html"},
{id:"bizxtreme",name:"BizXtreme",repo:"amerhwitat/BizXtreme",cat:"Games & Business",local:true,desc:"Extended game platform with UnifiedGame, AssetBrowser, NetworkUnified, economy, P2P and mobile tracks.",tags:["WebGL","P2P","Assets","Mobile"],url:"https://github.com/amerhwitat/BizXtreme",portal:"game-center.html"},
{id:"cpu4096",name:"CPU4096",repo:"amerhwitat/CPU4096",cat:"CPU & Simulation",local:true,desc:"4096/8192-bit wide-register research implementation with deterministic workloads and cross-language tracks.",tags:["C++","Java","Node","Python","8192-bit"],url:"https://github.com/amerhwitat/CPU4096",portal:"aurora_webgl_desktops.html"},
{id:"cpu4096sim",name:"CPU4096Simulator",repo:"amerhwitat/CPU4096Simulator",cat:"CPU & Simulation",local:true,desc:"Chimera II web/runtime simulator covering ISA, memory/MMIO, kernel/runtime, networking and robotics HAL.",tags:["JavaScript","Node","ISA","Web"],url:"https://github.com/amerhwitat/CPU4096Simulator",portal:"aurora_webgl_desktops.html"},
{id:"nlp",name:"Ancient Language NLP",repo:"amerhwitat/nlp",cat:"Language & Documents",local:true,desc:"Ancient-script scanning, OCR/media pipeline, transliteration, translation, reports and provenance-aware research.",tags:["OCR","NLP","PDF","Thamudic"],url:"https://github.com/amerhwitat/nlp",portal:"index.html#ocr"},
{id:"pdf",name:"PDFreaderPY",repo:"amerhwitat/PDFreaderPY",cat:"Language & Documents",local:true,desc:"Python PDF/document reader track integrated into the Chimera document workflow.",tags:["Python","PDF","Documents"],url:"https://github.com/amerhwitat/PDFreaderPY",portal:"index.html#pdf"},
{id:"general",name:"General Integration",repo:"amerhwitat/general",cat:"Integration",local:true,desc:"Shared network, AI, workflow, research, mobile, Apple and web integration material.",tags:["Network","AI","Workflow","Mobile"],url:"https://github.com/amerhwitat/general",portal:"network.html"},
{id:"keygen",name:"Koronos Java Track",repo:"amerhwitat/keygen",cat:"Runtime & Crypto",local:true,desc:"Java/Koronos 128D research runtime, services, concurrency and trusted-node federation.",tags:["Java","Koronos","128D"],url:"https://github.com/amerhwitat/keygen",portal:"aurora_3d_desktop.html"},
{id:"eth",name:"Ethereum Key Check",repo:"amerhwitat/eth-key-check",cat:"Runtime & Crypto",local:true,desc:"Owner-authorized cryptographic verification and cross-language research utilities.",tags:["Crypto","Python","Node","Java","C++"],url:"https://github.com/amerhwitat/eth-key-check",portal:"wallet-center.html"},
{id:"bruteforce",name:"Crypto Research",repo:"amerhwitat/bruteforce",cat:"Runtime & Crypto",local:true,desc:"Safe cryptographic research, restore-and-verify and synthetic benchmarking; no private-key recovery.",tags:["Crypto","AI","Benchmarks"],url:"https://github.com/amerhwitat/bruteforce",portal:"wallet-center.html"},
{id:"chimera",name:"ChimeraIIOS",repo:"amerhwitat/ChimeraIIOS",cat:"Core OS",local:true,desc:"Canonical OS, Aurora Control Center, emulation, games, network, NLP, PDF and runtime integration.",tags:["Aurora","MAME","Amiga","WebGL","PWA"],url:"https://github.com/amerhwitat/ChimeraIIOS",portal:"index.html"}
];
const $=s=>document.querySelector(s);const cats=[...new Set(apps.map(a=>a.cat))].sort();cats.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;$("#category").append(o)});
function render(){const q=$("#search").value.toLowerCase().trim(),c=$("#category").value,local=$("#localOnly").checked;const list=apps.filter(a=>(!q||[a.name,a.repo,a.desc,...a.tags].join(" ").toLowerCase().includes(q))&&(c==="all"||a.cat===c)&&(!local||a.local));$("#apps").innerHTML=list.length?list.map(a=>`<article class="card"><div class="meta">${a.cat} · ${a.repo}</div><h2>${a.name}</h2><p>${a.desc}</p><div class="tags">${a.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="actions"><a class="primary" href="${a.portal}">Open in Web UI</a><a href="${a.url}" target="_blank" rel="noopener">Source</a></div></article>`).join(""):`<div class="empty">No matching applications.</div>`};["input","change"].forEach(e=>document.addEventListener(e,render));render();